language: ruby
sudo: false
rvm:
  - 2.2
  - 2.0.0
  - 2.1
  - 1.9.3
script: "bundle exec rake test"
before_install:
 - gem update bundler
notifications:
  email:
    recipients:
      - salty@google.com
    on_success: change
    on_failure: change
